apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-jks-secret
  app: {{ template "spring-boot-webflux-k8s-http2-example.name" . }}
  chart: {{ template "spring-boot-webflux-k8s-http2-example.chart" . }}
  release: {{ .Release.Name }}
  heritage: {{ .Release.Service }}
type: Opaque
data:
  keystore.password: {{ .Values.env.tls.keystore.password | b64enc }}