apiVersion: v1
kind: Service
metadata:
  name: {{ template "spring-boot-webflux-k8s-http2-example.fullname" . }}
  labels:
    app: {{ template "spring-boot-webflux-k8s-http2-example.name" . }}
    chart: {{ template "spring-boot-webflux-k8s-http2-example.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
    - port: {{ .Values.env.server.http.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "spring-boot-webflux-k8s-http2-example.name" . }}
    release: {{ .Release.Name }}
